---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Pull Docker Image
      docker_image:
        name: sajalgupta545/calculator:latest
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: calculator-using-devops
        image: sajalgupta545/calculator
        state: started
        tty: yes
        interactive: yes

    - name: running container
      shell: docker run -it -d sajalgupta545/calculator

    #
    #    - name: running calculator container
    #      shell: docker run --rm -it -v ${PWD}/log:/log -d sajalgupta545/calculator:latest

    #